name: Deploy Terraform

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: indhiraPriyadarsini/github-reusables/.github/workflows/actions.yml@main
    with:
      terraform_version: "1.6.0"

      #...
