name: Deploy Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: https://github.com/indhiraPriyadarsini/github-reusables/.github/workflows/actions.yml@main
    with:
      terraform_version: "1.6.0"
      terraform_workspace: "dev"