name: Deploy Terraform

on:
 repository_dispatch:
    types: webhook

jobs:
  deploy:
    uses: indhiraPriyadarsini/github-reusables/.github/workflows/actions.yml@main
    with:
      terraform_version: "1.6.0"

      #...
